package dev.teyru.compiler.core.emitter;

import java.nio.charset.StandardCharsets;
import java.security.*;
import java.util.*;
import dev.teyru.compiler.core.budget.*;
import dev.teyru.compiler.core.diagnostic.*;
import dev.teyru.compiler.core.lowering.GeneratedFile;
import dev.teyru.compiler.core.semantic.BoundCompilationUnit;
import dev.teyru.compiler.core.semantic.BoundCompilationUnit.*;
import dev.teyru.compiler.core.source.*;
import dev.teyru.compiler.core.sourcemap.*;
import dev.teyru.compiler.core.symbol.*;
import dev.teyru.compiler.core.syntax.NodeId;

public final class DeterministicJavaEmitter implements JavaEmitter {
  public EmitResult emit(
      BoundCompilationUnit unit,
      EmitOptions options,
      ResourceTracker resources,
      CancellationToken cancellation) {
    var files = new ArrayList<GeneratedFile>();
    var diagnostics = new ArrayList<Diagnostic>();
    for (var type : unit.classes()) {
      cancellation.throwIfCancelled();
      var writer = new Writer(unit, options, type, diagnostics);
      String java = writer.emit();
      if (!diagnostics.isEmpty()) continue;
      byte[] bytes = java.getBytes(StandardCharsets.UTF_8);
      resources.addBytes(bytes.length);
      String uri =
          (unit.packageName().isBlank() ? "" : unit.packageName().replace('.', '/') + "/")
              + type.name()
              + ".java";
      files.add(
          new GeneratedFile(
              unit.source(),
              uri,
              java,
              new SourceMap(1, Map.of(uri, sha(bytes)), writer.segments),
              sha(bytes)));
    }
    return new EmitResult(files, diagnostics);
  }

  private static String sha(byte[] bytes) {
    try {
      return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException(e);
    }
  }

  private static final class Writer {
    final BoundCompilationUnit unit;
    final EmitOptions options;
    final BoundClass type;
    final List<Diagnostic> diagnostics;
    final StringBuilder out = new StringBuilder();
    final List<SourceMapSegment> segments = new ArrayList<>();

    Writer(BoundCompilationUnit u, EmitOptions o, BoundClass t, List<Diagnostic> d) {
      unit = u;
      options = o;
      type = t;
      diagnostics = d;
    }

    String emit() {
      int headerStart = codePoints();
      line("// Generated by Teyru " + options.generatorVersion());
      line(
          "// Source: "
              + unit.source().workspaceRelativeUri()
              + " sha256="
              + unit.source().contentSha256());
      map(
          headerStart,
          codePoints(),
          type.node(),
          Optional.of(syntheticOrigin(type.node(), "generated-header")),
          MappingKind.SYNTHETIC,
          "generated file header");
      if (!unit.packageName().isBlank()) {
        line("package " + unit.packageName() + ";");
        line("");
      }
      for (String i : unit.imports()) line("import " + i + ";");
      if (!unit.imports().isEmpty()) line("");
      int classStart = codePoints();
      line(prefix(type.visibility()) + "class " + type.name() + " {");
      map(
          classStart,
          codePoints(),
          type.node(),
          Optional.of(syntheticOrigin(type.node(), "class-boilerplate")),
          MappingKind.SYNTHETIC,
          "generated class declaration tokens");
      for (var member : type.members()) {
        int start = codePoints();
        if (member instanceof BoundField f) field(f, 1);
        else if (member instanceof BoundProperty p) property(p);
        else if (member instanceof BoundMethod m) method(m, 1);
        boolean generatedProperty = member instanceof BoundProperty;
        map(
            start,
            codePoints(),
            member.node(),
            generatedProperty
                ? Optional.of(((BoundProperty) member).descriptor().origin())
                : Optional.empty(),
            generatedProperty ? MappingKind.EXPANDED : MappingKind.DIRECT,
            "member emission");
      }
      int closeStart = codePoints();
      line("}");
      map(
          closeStart,
          codePoints(),
          type.node(),
          Optional.of(syntheticOrigin(type.node(), "class-close")),
          MappingKind.SYNTHETIC,
          "generated class closing token");
      return out.toString();
    }

    void field(BoundField f, int depth) {
      indent(depth);
      out.append(prefix(f.visibility()))
          .append(joinModifiers(f.modifiers()))
          .append(f.type())
          .append(' ')
          .append(f.name());
      f.initializer()
          .ifPresent(
              x -> {
                out.append(" = ");
                int start = codePoints();
                out.append(expr(x, null));
                map(
                    start,
                    codePoints(),
                    x.node(),
                    Optional.empty(),
                    MappingKind.DIRECT,
                    "field initializer");
              });
      out.append(";\n");
    }

    void property(BoundProperty p) {
      if (p.descriptor().kind() == PropertyDescriptor.PropertyKind.STORED) {
        int componentStart = codePoints();
        indent(1);
        out.append("private ")
            .append(joinModifiers(p.modifiers()))
            .append(p.type())
            .append(' ')
            .append(p.name());
        p.initializer()
            .ifPresent(
                x -> {
                  out.append(" = ");
                  int start = codePoints();
                  out.append(expr(x, p));
                  map(
                      start,
                      codePoints(),
                      x.node(),
                      Optional.empty(),
                      MappingKind.DIRECT,
                      "property initializer");
                });
        out.append(";\n");
        map(
            componentStart,
            codePoints(),
            p.node(),
            Optional.of(componentOrigin(p, "property-storage")),
            MappingKind.EXPANDED,
            "property backing field");
      }
      p.getter()
          .ifPresent(
              a -> {
                int componentStart = codePoints();
                indent(1);
                out.append(prefix(a.visibility().isBlank() ? p.visibility() : a.visibility()))
                    .append(p.type())
                    .append(" ")
                    .append(getter(p.name()))
                    .append("() {\n");
                if (a.defaultBody()) {
                  indent(2);
                  out.append("return this.").append(p.name()).append(";\n");
                } else statements(a.body(), 2, p);
                indent(1);
                out.append("}\n");
                map(
                    componentStart,
                    codePoints(),
                    p.node(),
                    Optional.of(componentOrigin(p, "property-getter")),
                    MappingKind.EXPANDED,
                    "property getter");
              });
      p.setter()
          .ifPresent(
              a -> {
                int componentStart = codePoints();
                indent(1);
                out.append(prefix(a.visibility().isBlank() ? p.visibility() : a.visibility()))
                    .append("void set")
                    .append(cap(p.name()))
                    .append('(')
                    .append(p.type())
                    .append(' ')
                    .append(a.parameterName())
                    .append(") {\n");
                if (a.defaultBody()) {
                  indent(2);
                  out.append("this.")
                      .append(p.name())
                      .append(" = ")
                      .append(a.parameterName())
                      .append(";\n");
                } else statements(a.body(), 2, p);
                indent(1);
                out.append("}\n");
                map(
                    componentStart,
                    codePoints(),
                    p.node(),
                    Optional.of(componentOrigin(p, "property-setter")),
                    MappingKind.EXPANDED,
                    "property setter");
              });
    }

    void method(BoundMethod m, int depth) {
      indent(depth);
      out.append(prefix(m.visibility()))
          .append(joinModifiers(m.modifiers()))
          .append(m.type())
          .append(' ')
          .append(m.name())
          .append('(');
      for (int i = 0; i < m.parameters().size(); i++) {
        if (i > 0) out.append(", ");
        var p = m.parameters().get(i);
        out.append(p.type()).append(' ').append(p.name());
      }
      out.append(") {\n");
      statements(m.body(), depth + 1, null);
      indent(depth);
      out.append("}\n");
    }

    void statements(List<BoundStatement> body, int depth, BoundProperty context) {
      for (var s : body) {
        if (s instanceof BoundReturn r) {
          indent(depth);
          out.append("return");
          r.value()
              .ifPresent(
                  v -> {
                    out.append(' ');
                    int start = codePoints();
                    out.append(expr(v, context));
                    map(
                        start,
                        codePoints(),
                        v.node(),
                        Optional.empty(),
                        MappingKind.DIRECT,
                        "return expression");
                  });
          out.append(";\n");
        } else if (s instanceof BoundLocal l) {
          indent(depth);
          out.append(
                  l.keyword().equals("val")
                      ? "final var"
                      : l.keyword().equals("var") ? "var" : l.explicitType())
              .append(' ')
              .append(l.name())
              .append(" = ");
          int start = codePoints();
          out.append(expr(l.initializer(), context));
          map(
              start,
              codePoints(),
              l.initializer().node(),
              Optional.empty(),
              MappingKind.DIRECT,
              "local initializer");
          out.append(";\n");
        } else if (s instanceof BoundExpressionStatement e) {
          indent(depth);
          int start = codePoints();
          if (e.expression() instanceof Assignment a
              && a.target() instanceof Member m
              && m.property().isPresent())
            out.append(expr(m.receiver(), context))
                .append(".set")
                .append(cap(m.property().orElseThrow().property().simpleName()))
                .append('(')
                .append(expr(a.value(), context))
                .append(')');
          else out.append(expr(e.expression(), context));
          map(
              start,
              codePoints(),
              e.expression().node(),
              Optional.empty(),
              MappingKind.DIRECT,
              "expression statement");
          out.append(";\n");
        } else if (s instanceof BoundIf i) {
          indent(depth);
          out.append("if (");
          int start = codePoints();
          out.append(expr(i.condition(), context));
          map(
              start,
              codePoints(),
              i.condition().node(),
              Optional.empty(),
              MappingKind.DIRECT,
              "if condition");
          out.append(") {\n");
          statements(i.whenTrue(), depth + 1, context);
          indent(depth);
          out.append("} else {\n");
          statements(i.whenFalse(), depth + 1, context);
          indent(depth);
          out.append("}\n");
        }
      }
    }

    GeneratedMemberOrigin componentOrigin(BoundProperty property, String feature) {
      return new GeneratedMemberOrigin(
          property.descriptor().origin().source(),
          property.node(),
          GeneratedMemberOrigin.OriginKind.PROPERTY_EXPANSION,
          feature);
    }

    GeneratedMemberOrigin syntheticOrigin(NodeId node, String feature) {
      return new GeneratedMemberOrigin(
          unit.source(), node, GeneratedMemberOrigin.OriginKind.COMPILER_SYNTHETIC, feature);
    }

    String expr(BoundExpression e, BoundProperty context) {
      if (e instanceof Literal x) return x.javaText();
      if (e instanceof Name x) {
        if (context != null && x.javaName().equals("field")) return "this." + context.name();
        return x.javaName();
      }
      if (e instanceof Member x) {
        String receiver = expr(x.receiver(), context);
        return x.property().isPresent()
            ? receiver + "." + getter(x.property().orElseThrow().property().simpleName()) + "()"
            : receiver + "." + x.javaName();
      }
      if (e instanceof Call x)
        return expr(x.target(), context)
            + "("
            + x.arguments().stream()
                .map(a -> expr(a, context))
                .collect(java.util.stream.Collectors.joining(", "))
            + ")";
      if (e instanceof NewObject x)
        return "new "
            + x.typeName()
            + "("
            + x.arguments().stream()
                .map(a -> expr(a, context))
                .collect(java.util.stream.Collectors.joining(", "))
            + ")";
      if (e instanceof Cast x) return "(" + x.typeName() + ") " + expr(x.value(), context);
      if (e instanceof Unary x) return x.operator() + expr(x.value(), context);
      if (e instanceof Binary x) {
        if (Set.of("++", "--", "+=", "-=", "*=", "/=").contains(x.operator()))
          return unsupported(x.node(), "compound-operation");
        return "("
            + expr(x.left(), context)
            + " "
            + x.operator()
            + " "
            + expr(x.right(), context)
            + ")";
      }
      if (e instanceof Assignment x) {
        if (x.target() instanceof Member m && m.property().isPresent())
          return unsupported(x.node(), "property-assignment-expression");
        return expr(x.target(), context) + " = " + expr(x.value(), context);
      }
      throw new IllegalStateException();
    }

    String unsupported(NodeId node, String feature) {
      diagnostics.add(
          new Diagnostic(
              1,
              new DiagnosticCode("TY-DEV-0001"),
              Severity.ERROR,
              unit.source(),
              node.rawRange(),
              "unsupported " + feature,
              List.of(),
              Map.of("feature", feature, "stage", "P06")));
      return "/* unsupported */";
    }

    void map(
        int a,
        int b,
        NodeId node,
        Optional<GeneratedMemberOrigin> origin,
        MappingKind kind,
        String reason) {
      TextRange raw = node.rawRange();
      int
          start =
              unit.sourceFile()
                  .convertBoundary(
                      raw.startOffset(),
                      OffsetUnit.RAW_UTF16,
                      OffsetUnit.UNICODE_CODE_POINT,
                      Bias.START),
          end =
              unit.sourceFile()
                  .convertBoundary(
                      raw.endOffset(),
                      OffsetUnit.RAW_UTF16,
                      OffsetUnit.UNICODE_CODE_POINT,
                      Bias.END);
      segments.add(
          new SourceMapSegment(
              new GeneratedRange(relative(), new TextRange(OffsetUnit.UNICODE_CODE_POINT, a, b)),
              List.of(
                  new SourceLocation(
                      unit.source(), new TextRange(OffsetUnit.UNICODE_CODE_POINT, start, end))),
              kind,
              node,
              origin,
              0,
              reason));
    }

    String relative() {
      return (unit.packageName().isBlank() ? "" : unit.packageName().replace('.', '/') + "/")
          + type.name()
          + ".java";
    }

    int codePoints() {
      return out.codePointCount(0, out.length());
    }

    void indent(int n) {
      out.append(options.indent().repeat(n));
    }

    void line(String s) {
      out.append(s).append('\n');
    }

    static String prefix(String x) {
      return x == null || x.isBlank() ? "" : x + " ";
    }

    static String joinModifiers(List<String> x) {
      return x.isEmpty() ? "" : String.join(" ", x) + " ";
    }

    static String cap(String n) {
      return n.length() > 1
              && Character.isUpperCase(n.charAt(0))
              && Character.isUpperCase(n.charAt(1))
          ? n
          : Character.toUpperCase(n.charAt(0)) + n.substring(1);
    }

    static String getter(String n) {
      return "get" + cap(n);
    }
  }
}
