// Package codegen lowers a checked Teyru program to portable C.
//
// The generated C is compiled to a native executable (optionally through LLVM)
// with no JVM involved: classes become C structs, virtual dispatch becomes a
// vtable, garbage collection is a conservative mark-and-sweep runtime.
package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/LangYa466/Teyru/internal/ast"
	"github.com/LangYa466/Teyru/internal/sema"
)

// Emitter produces one C translation unit for a whole program.
type Emitter struct {
	prog        *sema.Program
	types       strings.Builder // typedefs and struct declarations
	fns         strings.Builder // forward declarations
	code        *strings.Builder // function bodies
	data        strings.Builder // globals: strings, class metadata
	strings     map[string]int
	strOrder    []string
	mainCls     *ast.Class
	tmp         int
	indent      int
	thrown      []string
	locals      map[*ast.Var]string
	enumOrdinal string
}

// Emit returns the C source for a program.
func Emit(p *sema.Program) string {
	e := &Emitter{prog: p, strings: map[string]int{}, locals: map[*ast.Var]string{}, code: &strings.Builder{}}
	e.run()
	var out strings.Builder
	out.WriteString("/* generated by the Teyru compiler */\n")
	out.WriteString("#include \"tyrt.h\"\n#include <math.h>\n#include <string.h>\n\n")
	out.WriteString(e.types.String())
	out.WriteString(e.fns.String())
	out.WriteString(e.data.String())
	out.WriteString(e.code.String())
	out.WriteString(e.entry())
	return out.String()
}

func (e *Emitter) run() {
	for _, cl := range e.prog.Classes {
		e.declareClass(cl)
	}
	for _, cl := range e.prog.Classes {
		e.emitClassMeta(cl)
	}
	for _, cl := range e.prog.Classes {
		e.emitClassCode(cl)
	}
}

// ---------------------------------------------------------------- naming

// cname mangles a class's full name into a C identifier.
func cname(cl *ast.Class) string {
	return "C_" + mangle(cl.Full)
}

func mangle(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c == '_' || (i > 0 && c >= '0' && c <= '9'):
			b.WriteByte(c)
		case c == '.' || c == '$':
			b.WriteByte('_')
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

func fnName(cl *ast.Class, m *ast.Method, idx int) string {
	owner := ""
	if cl != nil {
		owner = mangle(cl.Full)
	}
	name := m.Name
	if m.IsCtor {
		name = "init"
	}
	if m.Accessor != nil && m.Prop != nil {
		if m.Accessor.IsSet {
			name = "set_" + m.Prop.Name
		} else {
			name = "get_" + m.Prop.Name
		}
	}
	return "M_" + owner + "_" + mangle(name) + "_" + fmt.Sprint(idx)
}

// methodIndex finds the position of m among the same-named methods of its owner.
func methodIndex(m *ast.Method) int {
	if m.Owner == nil {
		return 0
	}
	for i, x := range m.Owner.Methods[m.Name] {
		if x == m {
			return i
		}
	}
	for i, x := range m.Owner.Ctors {
		if x == m {
			return i
		}
	}
	return 0
}

func (e *Emitter) cfunc(m *ast.Method) string {
	if m.LLName == "" {
		m.LLName = fnName(m.Owner, m, methodIndex(m))
	}
	return m.LLName
}

// ---------------------------------------------------------------- C types

func (e *Emitter) ctype(t ast.Type) string {
	switch v := t.(type) {
	case nil:
		return "void"
	case *ast.PrimType:
		switch v.Kind {
		case ast.Void:
			return "void"
		case ast.Boolean:
			return "int32_t"
		case ast.Byte:
			return "int8_t"
		case ast.Short:
			return "int16_t"
		case ast.Char:
			return "uint16_t"
		case ast.Int:
			return "int32_t"
		case ast.Long:
			return "int64_t"
		case ast.Float:
			return "float"
		case ast.Double:
			return "double"
		}
		return "int32_t"
	case *ast.ClassType:
		return cname(v.Class) + "*"
	case *ast.ArrayType:
		return "tyarr*"
	case *ast.TypeVarType:
		return e.ctype(e.prog.Erased(v))
	case *ast.WildcardType:
		return "void*"
	case ast.NullType:
		return "void*"
	case ast.ErrorType:
		return "void*"
	}
	return "void*"
}

func (e *Emitter) isRef(t ast.Type) bool {
	switch t.(type) {
	case *ast.ClassType, *ast.ArrayType, ast.NullType, *ast.WildcardType:
		return true
	case *ast.TypeVarType:
		return true
	}
	return false
}

// zero renders the zero value of a C type.
func zeroOf(c string) string {
	switch c {
	case "int32_t", "int16_t", "uint16_t", "int8_t", "int64_t", "float", "double":
		return "0"
	}
	return "NULL"
}

// elemSize returns the byte size of an array element type.
func (e *Emitter) elemSize(t ast.Type) string {
	switch v := t.(type) {
	case *ast.PrimType:
		switch v.Kind {
		case ast.Boolean, ast.Int:
			return "4"
		case ast.Byte:
			return "1"
		case ast.Short:
			return "2"
		case ast.Char:
			return "2"
		case ast.Long:
			return "8"
		case ast.Float:
			return "4"
		case ast.Double:
			return "8"
		}
	case *ast.TypeVarType:
		return "8"
	}
	return "8"
}

func (e *Emitter) isRefElem(t ast.Type) bool { return e.isRef(t) }

// ---------------------------------------------------------------- class decls

func (e *Emitter) declareClass(cl *ast.Class) {
	switch cl.Special {
	case "String", "box", "sb":
		return // the runtime already defines this layout
	}
	fmt.Fprintf(&e.types, "typedef struct %s %s;\n", cname(cl), cname(cl))
}

func (e *Emitter) structOf(cl *ast.Class) string {
	switch cl.Special {
	case "String":
		return "typedef tystr " + cname(cl) + ";\n"
	case "sb":
		return "typedef tySB " + cname(cl) + ";\n"
	case "box":
		return "typedef " + boxStruct(cl) + " " + cname(cl) + ";\n"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "struct %s {\n  tyobj obj;\n", cname(cl))
	for _, f := range cl.InstFields {
		fmt.Fprintf(&b, "  %s f_%s;\n", e.ctype(f.Type), mangle(f.Name))
	}
	for _, v := range cl.CapFields {
		fmt.Fprintf(&b, "  %s cap_%s;\n", e.ctype(v.Type), mangle(v.Name))
	}
	b.WriteString("};\n")
	return b.String()
}

func (e *Emitter) emitClassMeta(cl *ast.Class) {
	e.types.WriteString(e.structOf(cl))
	e.emitStaticFields(cl)
	isIface := cl.IsInterface()
	flags := 0
	if isIface {
		flags |= 1
	}
	if cl.Special == "box" {
		flags |= 4
	}
	sup := "NULL"
	if cl.Super != nil {
		sup = "&cls_" + mangle(cl.Super.Class.Full)
	}
	// vtable
	var vt []string
	for _, m := range cl.VTable {
		vt = append(vt, "(void*)"+e.cfunc(m))
	}
	if len(vt) == 0 {
		vt = []string{"NULL"}
	}
	fmt.Fprintf(&e.data, "static void* vt_%s[%d] = {%s};\n", mangle(cl.Full), len(vt), strings.Join(vt, ", "))
	// interface table
	sel := e.prog.Selectors
	if sel == 0 {
		sel = 1
	}
	imap := make([]string, sel)
	for i := range imap {
		imap[i] = "NULL"
	}
	for _, iface := range e.prog.AllInterfaces(cl) {
		for _, m := range e.prog.InterfaceMethods(iface) {
			if m.Selector < 0 || m.Selector >= sel {
				continue
			}
			if impl := e.prog.Implements(cl, m); impl != nil {
				if _, isAbs := impl.SynthKind, false; isAbs {
					_ = isAbs
				}
				imap[m.Selector] = "(void*)" + e.cfunc(impl)
			}
		}
	}
	fmt.Fprintf(&e.data, "static tymap imap_%s[%d] = {%s};\n", mangle(cl.Full), sel, joinIMap(imap, sel))
	// ifaces list
	var ifs []string
	for _, i := range cl.Ifaces {
		ifs = append(ifs, "&cls_"+mangle(i.Class.Full))
	}
	if len(ifs) == 0 {
		ifs = []string{"NULL"}
	}
	fmt.Fprintf(&e.data, "static tyclass* if_%s[] = {%s};\n", mangle(cl.Full), strings.Join(ifs, ", "))
	// reference field offsets, following the C struct layout with alignment
	var offs []string
	off := int64(8)
	for _, f := range cl.InstFields {
		off = align(off, e.alignOf(f.Type))
		if e.isRef(f.Type) {
			offs = append(offs, fmt.Sprint(off))
		}
		off += e.sizeOf(f.Type)
	}
	for _, v := range sortedCaps(cl) {
		off = align(off, e.alignOf(v.Type))
		if e.isRef(v.Type) {
			offs = append(offs, fmt.Sprint(off))
		}
		off += e.sizeOf(v.Type)
	}
	off = align(off, 8)
	if len(offs) == 0 {
		offs = []string{"0"}
	}
	fmt.Fprintf(&e.data, "static int32_t refs_%s[] = {%s};\n", mangle(cl.Full), strings.Join(offs, ", "))
	clinit := "NULL"
	if cl.ClInit != nil {
		clinit = "(void*)" + e.cfunc(cl.ClInit)
	}
	fmt.Fprintf(&e.data, "static tyclass cls_%s = {%q, %d, %d, %s, %d, if_%s, %d, vt_%s, %s, %d, %d, imap_%s, 0, NULL, %d, refs_%s};\n",
		mangle(cl.Full), cl.Full, cl.ID, flags, sup, len(cl.Ifaces), mangle(cl.Full),
		len(cl.VTable), mangle(cl.Full), clinit, int(off), sel, mangle(cl.Full), len(offs), mangle(cl.Full))
	if cl.Outer != nil && cl.Inner {
	}
}

func joinIMap(entries []string, n int) string {
	if n == 0 {
		return "0"
	}
	parts := make([]string, n)
	for i := 0; i < n; i++ {
		parts[i] = fmt.Sprintf("{%d, %s}", i, entries[i])
	}
	return strings.Join(parts, ", ")
}

func boxStruct(cl *ast.Class) string {
	switch cl.Name {
	case "Integer":
		return "tyintbox"
	case "Long":
		return "tylongbox"
	case "Double":
		return "tydoublebox"
	case "Float":
		return "tyfloatbox"
	case "Character":
		return "tycharbox"
	case "Boolean":
		return "tyboolbox"
	case "Byte":
		return "tybytebox"
	case "Short":
		return "tyshortbox"
	}
	return "tyintbox"
}

func sortedCaps(cl *ast.Class) []*ast.Var {
	var out []*ast.Var
	for v := range cl.CapFields {
		out = append(out, v)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func align(off, a int64) int64 {
	if a <= 1 {
		return off
	}
	return (off + a - 1) / a * a
}

// alignOf returns the C alignment of a type.
func (e *Emitter) alignOf(t ast.Type) int64 {
	switch v := t.(type) {
	case *ast.PrimType:
		switch v.Kind {
		case ast.Byte, ast.Boolean:
			return 1
		case ast.Short, ast.Char:
			return 2
		case ast.Long, ast.Double:
			return 8
		}
		return 4
	}
	return 8
}

func (e *Emitter) sizeOf(t ast.Type) int64 {
	switch v := t.(type) {
	case *ast.PrimType:
		switch v.Kind {
		case ast.Boolean, ast.Int, ast.Float:
			return 4
		case ast.Byte:
			return 1
		case ast.Short, ast.Char:
			return 2
		case ast.Long, ast.Double:
			return 8
		}
		return 4
	}
	return 8
}

// ---------------------------------------------------------------- methods

func (e *Emitter) emitClassCode(cl *ast.Class) {
	e.emitClInit(cl)
	for _, name := range mangleOrder(cl) {
		for i, m := range cl.Methods[name] {
			e.emitMethod(cl, m, i)
		}
	}
	for i, m := range cl.Ctors {
		e.emitMethod(cl, m, i)
	}
}

func mangleOrder(cl *ast.Class) []string {
	var names []string
	for n := range cl.Methods {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// bodyOf returns the syntax body of a method, if any.
func bodyOf(m *ast.Method) *ast.Block {
	if m.Decl != nil && m.Decl.Body != nil {
		return m.Decl.Body
	}
	if m.Accessor != nil {
		return m.Accessor.Body
	}
	return nil
}

// signature renders the C declaration of a method.
func (e *Emitter) signature(m *ast.Method) string {
	ret := e.ctype(m.Result)
	if m.IsCtor {
		ret = "void"
	}
	var params []string
	if !m.IsStatic() {
		params = append(params, cname(m.Owner)+"* this")
	}
	for i, p := range m.Params {
		params = append(params, fmt.Sprintf("%s a%d", e.ctype(p), i))
	}
	if len(params) == 0 {
		params = append(params, "void")
	}
	return fmt.Sprintf("%s %s(%s)", ret, e.cfunc(m), strings.Join(params, ", "))
}

func (e *Emitter) emitMethod(cl *ast.Class, m *ast.Method, idx int) {
	if m.SynthKind == "lambda" || m.SynthKind == "lambda-ctor" {
		e.emitLambdaMethod(cl, m)
		return
	}
	if m.External {
		return
	}
	fmt.Fprintf(&e.fns, "static %s;\n", e.signature(m))
	body := bodyOf(m)
	if body == nil && !m.IsCtor && m.SynthKind != "" {
		e.emitSynthetic(cl, m)
		return
	}
	if body == nil && !m.IsCtor && m.Decl != nil {
		e.emitSynthetic(cl, m)
		return
	}
	e.indent = 0
	fmt.Fprintf(e.code, "static %s {\n", e.signature(m))
	e.indent++
	for i, pv := range m.ParamVars {
		e.locals[pv] = fmt.Sprintf("a%d", i)
	}
	if m.IsCtor {
		e.emitCtorBody(cl, m)
	} else if body != nil {
		e.emitBlockInner(body)
	} else {
		e.line("/* unimplemented */\n")
	}
	e.indent--
	e.code.WriteString("}\n\n")
}

// emitCtorBody writes field initializers, the super call and the body.
func (e *Emitter) emitCtorBody(cl *ast.Class, m *ast.Method) {
	e.line("\n")
	if cl.Super != nil {
		hasSuperCall := false
		if m.Decl != nil && m.Decl.Body != nil && len(m.Decl.Body.Stmts) > 0 {
			if c, ok := m.Decl.Body.Stmts[0].(*ast.ExprStmt); ok {
				if call, ok2 := c.X.(*ast.Call); ok2 && call.ThisCtor {
					hasSuperCall = true
				}
			}
		}
		if !hasSuperCall {
			sup := e.findSuperCtor(cl)
			if sup == nil && cl.Super.Class != e.prog.Builtins.Object {
				e.line("/* no accessible super constructor */\n")
			}
			if sup != nil {
				e.line("%s(%s);\n", e.cfunc(sup), e.args("this", nil, sup))
			}
		}
	}
	e.emitFieldInits(cl, m)
	if cl.Outer != nil && cl.Inner {
		// the outer instance is installed by the caller through a synthetic field
	}
	if m.Decl != nil && m.Decl.Body != nil {
		e.emitBlockInner(m.Decl.Body)
	}
	if m.Decl != nil && m.Decl.Compact {
		e.emitRecordAssign(cl, m)
		return
	}
	if m.SynthKind == "record-ctor" {
		e.emitRecordAssign(cl, m)
	}
}

func (e *Emitter) emitRecordAssign(cl *ast.Class, m *ast.Method) {
	for _, rc := range cl.Decl.RecordComps {
		f := cl.FieldMap[rc.Name]
		if f == nil {
			continue
		}
		e.line("this->f_%s = a%d;\n", mangle(f.Name), indexOfName(m.ParamNames, rc.Name))
	}
}

func indexOfName(names []string, n string) int {
	for i, x := range names {
		if x == n {
			return i
		}
	}
	return 0
}

// emitFieldInits runs instance field initializers in declaration order.
func (e *Emitter) emitFieldInits(cl *ast.Class, ctor *ast.Method) {
	if cl.Decl == nil {
		return
	}
	// superclass fields are initialized by the super constructor
	for _, mem := range cl.Decl.Members {
		fd, ok := mem.(*ast.FieldDecl)
		if !ok {
			continue
		}
		for _, vd := range fd.Vars {
			if vd.Init == nil || vd.Fld == nil || vd.Fld.Mods.Has(ast.ModStatic) {
				continue
			}
			target := "this->f_" + mangle(vd.Fld.Name)
			e.line("%s = %s;\n", target, e.coerce(e.expr(vd.Init), vd.Init.GetType(), vd.Fld.Type))
		}
	}
	for _, mem := range cl.Decl.Members {
		ib, ok := mem.(*ast.InitBlock)
		if !ok || ib.Static {
			continue
		}
		e.emitBlockInner(ib.Body)
	}
}

func (e *Emitter) findSuperCtor(cl *ast.Class) *ast.Method {
	sup := cl.Super.Class
	for _, c := range sup.Ctors {
		if len(c.Params) == 0 {
			return c
		}
	}
	if len(sup.Ctors) > 0 {
		return sup.Ctors[0]
	}
	return nil
}

// line writes an indented line of generated C.
func (e *Emitter) line(format string, args ...any) {
	for i := 0; i < e.indent; i++ {
		e.code.WriteString("  ")
	}
	fmt.Fprintf(e.code, format, args...)
}

func (e *Emitter) tmpName() string {
	e.tmp++
	return fmt.Sprintf("_t%d", e.tmp)
}

// entry emits main() and the startup sequence.
func (e *Emitter) entry() string {
	var b strings.Builder
	main := e.prog.Main
	b.WriteString("\nint main(int argc, char** argv) {\n  (void)argc; (void)argv;\n  ty_init();\n")
	b.WriteString(e.clinitRefs())
	b.WriteString("  TY_STRING = &cls_" + mangle(e.prog.Builtins.String.Full) + ";\n")
	b.WriteString("  TY_OBJECT = &cls_" + mangle(e.prog.Builtins.Object.Full) + ";\n")
	for k, cl := range e.prog.Builtins.Boxes {
		fmt.Fprintf(&b, "  TY_BOX[%d] = &cls_%s;\n", int(k), mangle(cl.Full))
	}
	for _, pair := range [][2]any{
		{"TY_NPE", e.prog.Builtins.NPE}, {"TY_AIOOBE", e.prog.Builtins.AIOOBE},
		{"TY_ARITH", e.prog.Builtins.Arith}, {"TY_CCE", e.prog.Builtins.CCE},
		{"TY_NEGARR", e.prog.Builtins.NegArr}, {"TY_ASSERT", e.prog.Builtins.Assertion},
		{"TY_ILLARG", e.prog.Builtins.IllArg}, {"TY_ILLSTATE", e.prog.Builtins.IllState},
		{"TY_NOSUCHELEM", e.prog.Builtins.NoSuchElem}, {"TY_UNSUP", e.prog.Builtins.Unsup},
	} {
		if cl, ok := pair[1].(*ast.Class); ok && cl != nil {
			fmt.Fprintf(&b, "  %s = &cls_%s;\n", pair[0], mangle(cl.Full))
		}
	}
	b.WriteString("  ty_clinit(&cls_" + mangle(e.prog.Builtins.Object.Full) + ");\n")
	seenInit := map[string]bool{}
	for _, cl := range e.prog.Classes {
		if cl.Builtin || seenInit[cname(cl)] {
			continue
		}
		seenInit[cname(cl)] = true
		fmt.Fprintf(&b, "  ty_clinit(&cls_%s);\n", mangle(cl.Full))
	}
	if main == nil {
		b.WriteString("  return 0;\n}\n")
		return b.String()
	}
	recv := ""
	if !main.IsStatic() {
		fmt.Fprintf(&b, "  %s _main_obj = (%s)ty_alloc(sizeof(%s));\n", cname(main.Owner), cname(main.Owner), cname(main.Owner))
		fmt.Fprintf(&b, "  _main_obj->obj.cls = &cls_%s;\n", mangle(main.Owner.Full))
		recv = "_main_obj, "
	}
	if len(main.Params) == 1 {
		b.WriteString("  tyarr* _args = ty_array_new(argc > 0 ? argc - 1 : 0, 8);\n")
		b.WriteString("  _args->refs = 1;\n")
		b.WriteString("  for (int _i = 1; _i < argc; _i++) ((void**)_args->data)[_i - 1] = (void*)ty_str_intern(argv[_i]);\n")
		fmt.Fprintf(&b, "  %s(%s_args);\n", e.cfunc(main), recv)
	} else {
		fmt.Fprintf(&b, "  %s(%s);\n", e.cfunc(main), strings.TrimSuffix(recv, ", "))
	}
	b.WriteString("  return 0;\n}\n")
	return b.String()
}

// emitStringTable writes the interned string literals collected so far.
func (e *Emitter) emitStringTable() string { return "" }

// capture runs fn with a fresh output buffer and returns what it wrote.
func (e *Emitter) capture(fn func()) string {
	old := e.code
	e.code = &strings.Builder{}
	fn()
	s := e.code.String()
	e.code = old
	return s
}
