[versions]
junit = "6.0.0"
lombok = "1.18.48"
lsp4j = "1.0.0"
intellij-platform = "2.18.1"
spotless = "8.10.2"
google-java-format = "1.36.0"
cyclonedx = "3.4.1"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
lombok-oracle = { module = "org.projectlombok:lombok", version.ref = "lombok" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
lsp4j-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version.ref = "lsp4j" }

[plugins]
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
